example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_json #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_xml #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_json_by_id #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_xml_by_id #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import register #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import logout_user, wishlist_ajax, wishlist_ajax_add #sesuaikan dengan nama fungsi yang dibuat

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit/', wishlist_ajax_add, name='wishlist_ajax_add'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Bryan Tjandra',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
    # return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    # return HttpResponse(serializers.serialize("json", data), content_type="application/json")
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@login_required(login_url='/wishlist/login/')
def wishlist_ajax(req):
    context = {
        'nama': 'Bryan Tjandra',
        'last_login': req.COOKIES['last_login'],
    }
    return render(req, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
@csrf_exempt
def wishlist_ajax_add(req):
    if req.method == "POST":
        nama = req.POST.get("nama")
        harga = req.POST.get("harga")
        deskripsi = req.POST.get("deskripsi")
        BarangWishlist.objects.create(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)
        return HttpResponse()
    else:
        print("here")
        return redirect("wishlist:show_wishlist")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/navbar.html
<div class="navbar bg-success shadow">
    <div class="container-fluid">
      <div class="d-flex w-100 justify-content-between">
        <span class="navbar-brand align-self-center">Wishlist</span>
        <div class="d-flex gap-4">
          <p class="align-self-center m-0">{{nama}}</p>
          <button class="border rounded border-info">
            <a href="{% url 'wishlist:logout' %}" class="text-decoration-none">Logout</a>
          </button>
        </div>
      </div>
    </div>
  </div>

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="p-4">
    <h5>Nama: </h5>
    <b>{{nama}}</b>
    <br>
    <br>
    <br>
    <table class="table table-bordered">
        <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
            <tr>
                <td>{{barang.nama_barang}}</td>
                <td>{{barang.harga_barang}}</td>
                <td>{{barang.deskripsi}}</td>
            </tr>
        {% endfor %}
    </table>
    <h5>Sesi terakhir login: {{ last_login }}</h5>
<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  function updateTable(){
    // clear table
    var itemCount = $(".table > tbody").children().length;
    for(var i = itemCount; i >= 2; i--){ // remove dara dari 2, karena 1 uuntuk header
      $(".table > tbody > tr:nth-child(" + i + ")").remove();
    }

    $.get("http://localhost:8000/wishlist/json/", function(data) {
      // fill table dr json
      for(var i = 0; i < data.length; i++){
        // buat row
        var tr = document.createElement("tr");
        
        // buat cell
        var cellNama = document.createElement("td");
        var cellHarga = document.createElement("td");
        var cellDeskripsi = document.createElement("td");

        // append data ke cell
        cellNama.append(data[i].fields.nama_barang);
        cellHarga.append(data[i].fields.harga_barang);
        cellDeskripsi.append(data[i].fields.deskripsi);
        
        // append cell ke row
        tr.append(cellNama);
        tr.append(cellHarga);
        tr.append(cellDeskripsi);
        
        // add ke tabel
        $(".table").append(tr);
      }
    });
  }
  
  $(document).ready(function(){
    updateTable();
    
    // untuk add wishlist
    $("#add_wishlist").click(function(){
      // get value nama harga desc
      var nama = $("#id_nama").val();
      var harga = $("#id_harga").val();
      var deskripsi = $("#id_deskripsi").val();

      
      $.post("http://localhost:8000/wishlist/ajax/submit/", // post data dengan routing
      // trus ke database
      {
        nama,
        harga,
        deskripsi,
      },
      function(data, status){
        console.log("add wishlist success");
        // update ulang table
        updateTable();
        // set form kosong
        $("#id_nama").val("");
        $("#id_harga").val("");
        $("#id_deskripsi").val("");
      });
    });
  });
</script>

{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="p-4">
    <h5>Nama: </h5>
    <b>{{nama}}</b>
    <br>
    <br>
    <br>
    <table class="table table-bordered">
        <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        
    </table>
    <h5>Sesi terakhir login: {{ last_login }}</h5>
    <h5 class="mt-4">Tambah Barang</h5>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
        <tr>
            <td>Nama Barang: </td>
            <td><input type="text" name="nama_barang" placeholder="Nama Barang" class="form-control" id="id_nama"></td>
        </tr>
        <tr>
            <td>Harga Barang: </td>
            <td><input type="text" name="harga_barang" placeholder="Harga Barang" class="form-control" id="id_harga"></td>
        </tr>
        <tr>
            <td>Deskripsi: </td>
            <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control" id="id_deskripsi"></td>
        </tr>
        </table>
        </form>
        <br>
        <button id="add_wishlist" class="btn border rounded bg-info">Tambah</button>
</div>

{% endblock content %}